### ISSUE TITLE
WhatsNew screen does not work on web

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#297]
### Package / App

Other

### Version

0.0.4

### What happened?

When navigating to what's new screen in chronicles (through demo mode on web), this pops up in the console:

![image](https://github.com/equinor/mad/assets/22524448/079d356d-f5c4-4964-8b7a-ead5c5519d6b)

```
react.development.js:209 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ChangeLog`.
    at ChangeLog (http://localhost:19006/static/js/bundle.js:277683:20)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at WhatsNewScreen (http://localhost:19006/static/js/bundle.js:277213:84)
    at StaticContainer (http://localhost:19006/static/js/bundle.js:7220:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:7110:21)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at Background (http://localhost:19006/static/js/bundle.js:10664:20)
    at Screen (http://localhost:19006/static/js/bundle.js:11761:100)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:11705:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:11883:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:7020:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:8435:21)
    at http://localhost:19006/static/js/bundle.js:8446:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:288562:5)
    at HeaderHeightProvider (http://localhost:19006/static/js/bundle.js:288408:31)
    at AnnouncementsProvider (http://localhost:19006/static/js/bundle.js:277762:32)
    at EnvironmentProvider (http://localhost:19006/static/js/bundle.js:290429:3)
    at MadCoreNavigator (http://localhost:19006/static/js/bundle.js:277856:405)
    at RootNavigator
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at BaseNavigationContainer (http://localhost:19006/static/js/bundle.js:6443:27)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:12473:20)
    at NavigationContainerInner (http://localhost:19006/static/js/bundle.js:12140:25)
    at NavigationContainer (http://localhost:19006/static/js/bundle.js:293977:108)
    at Navigation (http://localhost:19006/static/js/bundle.js:440:26)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:230487:5)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:273464:26)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at ScrimProvider (http://localhost:19006/static/js/bundle.js:276158:24)
    at PortalProvider (http://localhost:19006/static/js/bundle.js:276466:25)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at GestureHandlerRootView
    at EDSProvider (http://localhost:19006/static/js/bundle.js:272929:127)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:57399:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:57557:23)
    at App (http://localhost:19006/static/js/bundle.js:42:96)
    at withDevTools(App)
overrideMethod @ console.js:213
printWarning @ react.development.js:209
error @ react.development.js:183
createElementWithValidation @ react.development.js:2354
ChangeLog @ chunk-GFKSJVNT.js:31
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
Show less
react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ChangeLog`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
createFiberFromTypeAndProps @ react-dom.development.js:28439
createFiberFromElement @ react-dom.development.js:28465
reconcileSingleElement @ react-dom.development.js:15750
reconcileChildFibers @ react-dom.development.js:15808
reconcileChildren @ react-dom.development.js:19167
updateHostComponent @ react-dom.development.js:19924
beginWork @ react-dom.development.js:21618
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:209 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ChangeLog`.
    at ChangeLog (http://localhost:19006/static/js/bundle.js:277683:20)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at WhatsNewScreen (http://localhost:19006/static/js/bundle.js:277213:84)
    at StaticContainer (http://localhost:19006/static/js/bundle.js:7220:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:7110:21)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at Background (http://localhost:19006/static/js/bundle.js:10664:20)
    at Screen (http://localhost:19006/static/js/bundle.js:11761:100)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:11705:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:11883:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:7020:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:8435:21)
    at http://localhost:19006/static/js/bundle.js:8446:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:288562:5)
    at HeaderHeightProvider (http://localhost:19006/static/js/bundle.js:288408:31)
    at AnnouncementsProvider (http://localhost:19006/static/js/bundle.js:277762:32)
    at EnvironmentProvider (http://localhost:19006/static/js/bundle.js:290429:3)
    at MadCoreNavigator (http://localhost:19006/static/js/bundle.js:277856:405)
    at RootNavigator
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at BaseNavigationContainer (http://localhost:19006/static/js/bundle.js:6443:27)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:12473:20)
    at NavigationContainerInner (http://localhost:19006/static/js/bundle.js:12140:25)
    at NavigationContainer (http://localhost:19006/static/js/bundle.js:293977:108)
    at Navigation (http://localhost:19006/static/js/bundle.js:440:26)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:230487:5)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:273464:26)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at ScrimProvider (http://localhost:19006/static/js/bundle.js:276158:24)
    at PortalProvider (http://localhost:19006/static/js/bundle.js:276466:25)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at GestureHandlerRootView
    at EDSProvider (http://localhost:19006/static/js/bundle.js:272929:127)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:57399:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:57557:23)
    at App (http://localhost:19006/static/js/bundle.js:42:96)
    at withDevTools(App)
overrideMethod @ console.js:213
printWarning @ react.development.js:209
error @ react.development.js:183
createElementWithValidation @ react.development.js:2354
ChangeLog @ chunk-GFKSJVNT.js:31
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
Show less
react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ChangeLog`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
createFiberFromTypeAndProps @ react-dom.development.js:28439
createFiberFromElement @ react-dom.development.js:28465
reconcileSingleElement @ react-dom.development.js:15750
reconcileChildFibers @ react-dom.development.js:15808
reconcileChildren @ react-dom.development.js:19167
updateHostComponent @ react-dom.development.js:19924
beginWork @ react-dom.development.js:21618
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <div> component:

    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at Pressable (http://localhost:19006/static/js/bundle.js:63222:24)
    at http://localhost:19006/static/js/bundle.js:283632:7
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at http://localhost:19006/static/js/bundle.js:287284:7
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at http://localhost:19006/static/js/bundle.js:63587:24
    at ScrollView (http://localhost:19006/static/js/bundle.js:63737:86)
    at ScrollView
    at ChangeLog (http://localhost:19006/static/js/bundle.js:277683:20)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at WhatsNewScreen (http://localhost:19006/static/js/bundle.js:277213:84)
    at StaticContainer (http://localhost:19006/static/js/bundle.js:7220:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:7110:21)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at Background (http://localhost:19006/static/js/bundle.js:10664:20)
    at Screen (http://localhost:19006/static/js/bundle.js:11761:100)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:11705:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:11883:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:7020:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:8435:21)
    at http://localhost:19006/static/js/bundle.js:8446:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:288562:5)
    at HeaderHeightProvider (http://localhost:19006/static/js/bundle.js:288408:31)
    at AnnouncementsProvider (http://localhost:19006/static/js/bundle.js:277762:32)
    at EnvironmentProvider (http://localhost:19006/static/js/bundle.js:290429:3)
    at MadCoreNavigator (http://localhost:19006/static/js/bundle.js:277856:405)
    at RootNavigator
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6776:23)
    at BaseNavigationContainer (http://localhost:19006/static/js/bundle.js:6443:27)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:12473:20)
    at NavigationContainerInner (http://localhost:19006/static/js/bundle.js:12140:25)
    at NavigationContainer (http://localhost:19006/static/js/bundle.js:293977:108)
    at Navigation (http://localhost:19006/static/js/bundle.js:440:26)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:230487:5)
    at ErrorBoundary (http://localhost:19006/static/js/bundle.js:273464:26)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at PortalHostComponent (http://localhost:19006/static/js/bundle.js:273085:5)
    at ScrimProvider (http://localhost:19006/static/js/bundle.js:276158:24)
    at PortalProvider (http://localhost:19006/static/js/bundle.js:276466:25)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at GestureHandlerRootView
    at EDSProvider (http://localhost:19006/static/js/bundle.js:272929:127)
    at div
    at http://localhost:19006/static/js/bundle.js:67564:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:57399:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:57557:23)
    at App (http://localhost:19006/static/js/bundle.js:42:96)
    at withDevTools(App)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by tormodAase** [comment]
This looks like it was fixed by #298
